# permissions for end users to view plexmediaservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plexmediaserver-viewer-role
rules:
- apiGroups:
  - plex.adambkaplan.com
  resources:
  - plexmediaservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - plex.adambkaplan.com
  resources:
  - plexmediaservers/status
  verbs:
  - get
